import os
#import sipconfig
#from PyQt5 import pyqtconfig
from sipconfig import Configuration, ModuleMakefile
from PyQt5.QtCore import PYQT_CONFIGURATION


# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "trikControl.sbf"

# Get the SIP configuration information.
config = Configuration()

# Get the extra SIP flags needed by the imported PyQt4 modules.  Note that
# this normally only includes those flags (-x and -t) that relate to SIP's
# versioning system.
pyqt_sip_flags = PYQT_CONFIGURATION['sip_flags']
pyqt_sip_dir = '%s/PyQt5/' % config.default_sip_dir

# Run SIP to generate the code.

command = " ".join([config.sip_bin, "-c", ".", "-b", build_file, "-I", pyqt_sip_dir, pyqt_sip_flags, "brickFactory.sip"])
print(command)
#os.system(command) ## trikControl.sip

# Create the Makefile.
#makefile = ModuleMakefile(config, build_file)

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
#makefile.extra_libs = ["trikControl"]

# Generate the Makefile itself.
#makefile.generate()