/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 */

#include "sipAPItrikControl.h"

#line 6 "LedInterface.sip"
		#include <ledInterface.h>
#line 6 "EncoderInterface.sip"
		#include <encoderInterface.h>
#line 14 "./siptrikControltrikControlEncoderInterface.cpp"

#line 26 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 18 "./siptrikControltrikControlEncoderInterface.cpp"
#line 368 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 21 "./siptrikControltrikControlEncoderInterface.cpp"
#line 351 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 24 "./siptrikControltrikControlEncoderInterface.cpp"
#line 29 "/usr/share/sip/PyQt4//QtCore/qobject.sip"
#include <qobject.h>
#line 27 "./siptrikControltrikControlEncoderInterface.cpp"
#line 269 "/usr/share/sip/PyQt4//QtCore/qvariant.sip"
#include <qvariant.h>
#line 30 "./siptrikControltrikControlEncoderInterface.cpp"
#line 28 "/usr/share/sip/PyQt4//QtCore/qlist.sip"
#include <qlist.h>
#line 33 "./siptrikControltrikControlEncoderInterface.cpp"
#line 32 "/usr/share/sip/PyQt4//QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 36 "./siptrikControltrikControlEncoderInterface.cpp"
#line 30 "/usr/share/sip/PyQt4//QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 39 "./siptrikControltrikControlEncoderInterface.cpp"
#line 115 "/usr/share/sip/PyQt4//QtCore/qlist.sip"
#include <qlist.h>
#line 42 "./siptrikControltrikControlEncoderInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qthread.sip"
#include <qthread.h>
#line 45 "./siptrikControltrikControlEncoderInterface.cpp"
#line 31 "/usr/share/sip/PyQt4//QtCore/qstring.sip"
#include <qstring.h>
#line 48 "./siptrikControltrikControlEncoderInterface.cpp"
#line 30 "/usr/share/sip/PyQt4//QtCore/qregexp.sip"
#include <qregexp.h>
#line 51 "./siptrikControltrikControlEncoderInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 54 "./siptrikControltrikControlEncoderInterface.cpp"


extern "C" {static PyObject *meth_trikControl_EncoderInterface_read(PyObject *, PyObject *);}
static PyObject *meth_trikControl_EncoderInterface_read(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::EncoderInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_EncoderInterface, &sipCpp))
        {
            int sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_EncoderInterface, sipName_read);
                return NULL;
            }

            sipRes = sipCpp->read();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_EncoderInterface, sipName_read, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_EncoderInterface_readRawData(PyObject *, PyObject *);}
static PyObject *meth_trikControl_EncoderInterface_readRawData(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::EncoderInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_EncoderInterface, &sipCpp))
        {
            int sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_EncoderInterface, sipName_readRawData);
                return NULL;
            }

            sipRes = sipCpp->readRawData();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_EncoderInterface, sipName_readRawData, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_EncoderInterface_reset(PyObject *, PyObject *);}
static PyObject *meth_trikControl_EncoderInterface_reset(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::EncoderInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_EncoderInterface, &sipCpp))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_EncoderInterface, sipName_reset);
                return NULL;
            }

            sipCpp->reset();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_EncoderInterface, sipName_reset, NULL);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_trikControl_EncoderInterface(void *, int);}
static void release_trikControl_EncoderInterface(void *sipCppV,int)
{
    trikControl::EncoderInterface *sipCpp = reinterpret_cast<trikControl::EncoderInterface *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_trikControl_EncoderInterface(sipSimpleWrapper *);}
static void dealloc_trikControl_EncoderInterface(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_trikControl_EncoderInterface(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_trikControl_EncoderInterface[] = {{141, 0, 1}};


static PyMethodDef methods_trikControl_EncoderInterface[] = {
    {SIP_MLNAME_CAST(sipName_read), meth_trikControl_EncoderInterface_read, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_readRawData), meth_trikControl_EncoderInterface_readRawData, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_reset), meth_trikControl_EncoderInterface_reset, METH_VARARGS, NULL}
};


pyqt4ClassTypeDef sipTypeDef_trikControl_trikControl_EncoderInterface = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_trikControl__EncoderInterface,
        {0}
    },
    {
        sipNameNr_EncoderInterface,
        {0, 255, 0},
        3, methods_trikControl_EncoderInterface,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_trikControl_EncoderInterface,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_trikControl_EncoderInterface,
    0,
    0,
    0,
    release_trikControl_EncoderInterface,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    &trikControl::EncoderInterface::staticMetaObject,
    0,
    0
};
