/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 */

#include "sipAPItrikControl.h"

#line 12 "KeysInterface.sip"
		#include <keysInterface.h>
#line 12 "./siptrikControltrikControlKeysInterface.cpp"

#line 26 "/usr/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 16 "./siptrikControltrikControlKeysInterface.cpp"
#line 368 "/usr/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 19 "./siptrikControltrikControlKeysInterface.cpp"
#line 351 "/usr/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 22 "./siptrikControltrikControlKeysInterface.cpp"
#line 29 "/usr/share/sip/PyQt4/QtCore/qobject.sip"
#include <qobject.h>
#line 25 "./siptrikControltrikControlKeysInterface.cpp"
#line 269 "/usr/share/sip/PyQt4/QtCore/qvariant.sip"
#include <qvariant.h>
#line 28 "./siptrikControltrikControlKeysInterface.cpp"
#line 28 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 31 "./siptrikControltrikControlKeysInterface.cpp"
#line 32 "/usr/share/sip/PyQt4/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 34 "./siptrikControltrikControlKeysInterface.cpp"
#line 30 "/usr/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 37 "./siptrikControltrikControlKeysInterface.cpp"
#line 115 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 40 "./siptrikControltrikControlKeysInterface.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qthread.sip"
#include <qthread.h>
#line 43 "./siptrikControltrikControlKeysInterface.cpp"
#line 31 "/usr/share/sip/PyQt4/QtCore/qstring.sip"
#include <qstring.h>
#line 46 "./siptrikControltrikControlKeysInterface.cpp"
#line 30 "/usr/share/sip/PyQt4/QtCore/qregexp.sip"
#include <qregexp.h>
#line 49 "./siptrikControltrikControlKeysInterface.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 52 "./siptrikControltrikControlKeysInterface.cpp"


extern "C" {static PyObject *meth_trikControl_KeysInterface_reset(PyObject *, PyObject *);}
static PyObject *meth_trikControl_KeysInterface_reset(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::KeysInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_KeysInterface, &sipCpp))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_KeysInterface, sipName_reset);
                return NULL;
            }

            sipCpp->reset();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_KeysInterface, sipName_reset, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_KeysInterface_wasPressed(PyObject *, PyObject *);}
static PyObject *meth_trikControl_KeysInterface_wasPressed(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        int a0;
        trikControl::KeysInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_trikControl_KeysInterface, &sipCpp, &a0))
        {
            bool sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_KeysInterface, sipName_wasPressed);
                return NULL;
            }

            sipRes = sipCpp->wasPressed(a0);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_KeysInterface, sipName_wasPressed, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_KeysInterface_isPressed(PyObject *, PyObject *);}
static PyObject *meth_trikControl_KeysInterface_isPressed(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        int a0;
        trikControl::KeysInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_trikControl_KeysInterface, &sipCpp, &a0))
        {
            bool sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_KeysInterface, sipName_isPressed);
                return NULL;
            }

            sipRes = sipCpp->isPressed(a0);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_KeysInterface, sipName_isPressed, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_KeysInterface_buttonCode(PyObject *, PyObject *);}
static PyObject *meth_trikControl_KeysInterface_buttonCode(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        bool a0 = 1;
        trikControl::KeysInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B|b", &sipSelf, sipType_trikControl_KeysInterface, &sipCpp, &a0))
        {
            int sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_KeysInterface, sipName_buttonCode);
                return NULL;
            }

            sipRes = sipCpp->buttonCode(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_KeysInterface, sipName_buttonCode, NULL);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_trikControl_KeysInterface(void *, int);}
static void release_trikControl_KeysInterface(void *sipCppV,int)
{
    trikControl::KeysInterface *sipCpp = reinterpret_cast<trikControl::KeysInterface *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_trikControl_KeysInterface(sipSimpleWrapper *);}
static void dealloc_trikControl_KeysInterface(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_trikControl_KeysInterface(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_trikControl_KeysInterface[] = {{141, 0, 1}};


static PyMethodDef methods_trikControl_KeysInterface[] = {
    {SIP_MLNAME_CAST(sipName_buttonCode), meth_trikControl_KeysInterface_buttonCode, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_isPressed), meth_trikControl_KeysInterface_isPressed, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_reset), meth_trikControl_KeysInterface_reset, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_wasPressed), meth_trikControl_KeysInterface_wasPressed, METH_VARARGS, NULL}
};


/* Define this type's signals. */
static const pyqt4QtSignal signals_trikControl_KeysInterface[] = {
    {"buttonPressed(int,int)", 0, 0, 0},
    {0, 0, 0, 0}
};


pyqt4ClassTypeDef sipTypeDef_trikControl_trikControl_KeysInterface = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_trikControl__KeysInterface,
        {0}
    },
    {
        sipNameNr_KeysInterface,
        {0, 255, 0},
        4, methods_trikControl_KeysInterface,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_trikControl_KeysInterface,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_trikControl_KeysInterface,
    0,
    0,
    0,
    release_trikControl_KeysInterface,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    &trikControl::KeysInterface::staticMetaObject,
    0,
    signals_trikControl_KeysInterface,
};
