/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 */

#include "sipAPItrikControl.h"

#line 9 "SensorInterface.sip"
		#include <sensorInterface.h>
#line 12 "./siptrikControltrikControlSensorInterface.cpp"

#line 26 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 16 "./siptrikControltrikControlSensorInterface.cpp"
#line 368 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 19 "./siptrikControltrikControlSensorInterface.cpp"
#line 351 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 22 "./siptrikControltrikControlSensorInterface.cpp"
#line 29 "/usr/share/sip/PyQt4//QtCore/qobject.sip"
#include <qobject.h>
#line 25 "./siptrikControltrikControlSensorInterface.cpp"
#line 269 "/usr/share/sip/PyQt4//QtCore/qvariant.sip"
#include <qvariant.h>
#line 28 "./siptrikControltrikControlSensorInterface.cpp"
#line 28 "/usr/share/sip/PyQt4//QtCore/qlist.sip"
#include <qlist.h>
#line 31 "./siptrikControltrikControlSensorInterface.cpp"
#line 32 "/usr/share/sip/PyQt4//QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 34 "./siptrikControltrikControlSensorInterface.cpp"
#line 30 "/usr/share/sip/PyQt4//QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 37 "./siptrikControltrikControlSensorInterface.cpp"
#line 115 "/usr/share/sip/PyQt4//QtCore/qlist.sip"
#include <qlist.h>
#line 40 "./siptrikControltrikControlSensorInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qthread.sip"
#include <qthread.h>
#line 43 "./siptrikControltrikControlSensorInterface.cpp"
#line 31 "/usr/share/sip/PyQt4//QtCore/qstring.sip"
#include <qstring.h>
#line 46 "./siptrikControltrikControlSensorInterface.cpp"
#line 30 "/usr/share/sip/PyQt4//QtCore/qregexp.sip"
#include <qregexp.h>
#line 49 "./siptrikControltrikControlSensorInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 52 "./siptrikControltrikControlSensorInterface.cpp"


extern "C" {static PyObject *meth_trikControl_SensorInterface_minValue(PyObject *, PyObject *);}
static PyObject *meth_trikControl_SensorInterface_minValue(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const trikControl::SensorInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_SensorInterface, &sipCpp))
        {
            int sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_SensorInterface, sipName_minValue);
                return NULL;
            }

            sipRes = sipCpp->minValue();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SensorInterface, sipName_minValue, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_SensorInterface_maxValue(PyObject *, PyObject *);}
static PyObject *meth_trikControl_SensorInterface_maxValue(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const trikControl::SensorInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_SensorInterface, &sipCpp))
        {
            int sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_SensorInterface, sipName_maxValue);
                return NULL;
            }

            sipRes = sipCpp->maxValue();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SensorInterface, sipName_maxValue, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_SensorInterface_read(PyObject *, PyObject *);}
static PyObject *meth_trikControl_SensorInterface_read(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::SensorInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_SensorInterface, &sipCpp))
        {
            int sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_SensorInterface, sipName_read);
                return NULL;
            }

            sipRes = sipCpp->read();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SensorInterface, sipName_read, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_SensorInterface_readRawData(PyObject *, PyObject *);}
static PyObject *meth_trikControl_SensorInterface_readRawData(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::SensorInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_SensorInterface, &sipCpp))
        {
            int sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_SensorInterface, sipName_readRawData);
                return NULL;
            }

            sipRes = sipCpp->readRawData();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SensorInterface, sipName_readRawData, NULL);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_trikControl_SensorInterface(void *, int);}
static void release_trikControl_SensorInterface(void *sipCppV,int)
{
    trikControl::SensorInterface *sipCpp = reinterpret_cast<trikControl::SensorInterface *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_trikControl_SensorInterface(sipSimpleWrapper *);}
static void dealloc_trikControl_SensorInterface(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_trikControl_SensorInterface(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_trikControl_SensorInterface[] = {{141, 0, 1}};


static PyMethodDef methods_trikControl_SensorInterface[] = {
    {SIP_MLNAME_CAST(sipName_maxValue), meth_trikControl_SensorInterface_maxValue, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_minValue), meth_trikControl_SensorInterface_minValue, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_read), meth_trikControl_SensorInterface_read, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_readRawData), meth_trikControl_SensorInterface_readRawData, METH_VARARGS, NULL}
};

static sipEnumMemberDef enummembers_trikControl_SensorInterface[] = {
    {sipName_analogSensor, static_cast<int>(trikControl::SensorInterface::Type::analogSensor), 14},
    {sipName_digitalSensor, static_cast<int>(trikControl::SensorInterface::Type::digitalSensor), 14},
    {sipName_specialSensor, static_cast<int>(trikControl::SensorInterface::Type::specialSensor), 14},
};


pyqt4ClassTypeDef sipTypeDef_trikControl_trikControl_SensorInterface = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_trikControl__SensorInterface,
        {0}
    },
    {
        sipNameNr_SensorInterface,
        {0, 255, 0},
        4, methods_trikControl_SensorInterface,
        3, enummembers_trikControl_SensorInterface,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_trikControl_SensorInterface,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_trikControl_SensorInterface,
    0,
    0,
    0,
    release_trikControl_SensorInterface,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    &trikControl::SensorInterface::staticMetaObject,
    0,
    0
};
