/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 */

#include "sipAPItrikControl.h"

#line 7 "TimeVal.sip"
		#include <timeVal.h>
#line 12 "./siptrikControltrikKernelTimeVal.cpp"



extern "C" {static PyObject *meth_trikKernel_TimeVal_toMcSec(PyObject *, PyObject *);}
static PyObject *meth_trikKernel_TimeVal_toMcSec(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const trikKernel::TimeVal *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikKernel_TimeVal, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->toMcSec();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_TimeVal, sipName_toMcSec, NULL);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_trikKernel_TimeVal(void *, int);}
static void release_trikKernel_TimeVal(void *sipCppV,int)
{
    delete reinterpret_cast<trikKernel::TimeVal *>(sipCppV);
}


extern "C" {static void assign_trikKernel_TimeVal(void *, SIP_SSIZE_T, const void *);}
static void assign_trikKernel_TimeVal(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<trikKernel::TimeVal *>(sipDst)[sipDstIdx] = *reinterpret_cast<const trikKernel::TimeVal *>(sipSrc);
}


extern "C" {static void *array_trikKernel_TimeVal(SIP_SSIZE_T);}
static void *array_trikKernel_TimeVal(SIP_SSIZE_T sipNrElem)
{
    return new trikKernel::TimeVal[sipNrElem];
}


extern "C" {static void *copy_trikKernel_TimeVal(const void *, SIP_SSIZE_T);}
static void *copy_trikKernel_TimeVal(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new trikKernel::TimeVal(reinterpret_cast<const trikKernel::TimeVal *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_trikKernel_TimeVal(sipSimpleWrapper *);}
static void dealloc_trikKernel_TimeVal(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_trikKernel_TimeVal(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_type_trikKernel_TimeVal(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_trikKernel_TimeVal(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    trikKernel::TimeVal *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new trikKernel::TimeVal();

            return sipCpp;
        }
    }

    {
        const trikKernel::TimeVal* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_trikKernel_TimeVal, &a0))
        {
            sipCpp = new trikKernel::TimeVal(*a0);

            return sipCpp;
        }
    }

    {
        int a0;
        int a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "ii", &a0, &a1))
        {
            sipCpp = new trikKernel::TimeVal(a0,a1);

            return sipCpp;
        }
    }

    return NULL;
}


static PyMethodDef methods_trikKernel_TimeVal[] = {
    {SIP_MLNAME_CAST(sipName_toMcSec), meth_trikKernel_TimeVal_toMcSec, METH_VARARGS, NULL}
};


pyqt4ClassTypeDef sipTypeDef_trikControl_trikKernel_TimeVal = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_trikKernel__TimeVal,
        {0}
    },
    {
        sipNameNr_TimeVal,
        {15, 255, 0},
        1, methods_trikKernel_TimeVal,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    -1,
    0,
    0,
    init_type_trikKernel_TimeVal,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_trikKernel_TimeVal,
    assign_trikKernel_TimeVal,
    array_trikKernel_TimeVal,
    copy_trikKernel_TimeVal,
    release_trikKernel_TimeVal,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
