/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 */

#include "sipAPItrikControl.h"

#line 10 "ObjectSensorInterface.sip"
		#include <objectSensorInterface.h>
#line 12 "./siptrikControltrikControlObjectSensorInterface.cpp"

#line 101 "/usr/share/sip/PyQt4//QtCore/qvector.sip"
#include <qvector.h>
#line 16 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 19 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 368 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 22 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 351 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 25 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 29 "/usr/share/sip/PyQt4//QtCore/qobject.sip"
#include <qobject.h>
#line 28 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 265 "/usr/share/sip/PyQt4//QtCore/qvariant.sip"
#include <qvariant.h>
#line 31 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 28 "/usr/share/sip/PyQt4//QtCore/qlist.sip"
#include <qlist.h>
#line 34 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 32 "/usr/share/sip/PyQt4//QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 37 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 40 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 115 "/usr/share/sip/PyQt4//QtCore/qlist.sip"
#include <qlist.h>
#line 43 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qthread.sip"
#include <qthread.h>
#line 46 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 27 "/usr/share/sip/PyQt4//QtCore/qstring.sip"
#include <qstring.h>
#line 49 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qregexp.sip"
#include <qregexp.h>
#line 52 "./siptrikControltrikControlObjectSensorInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 55 "./siptrikControltrikControlObjectSensorInterface.cpp"


extern "C" {static PyObject *meth_trikControl_ObjectSensorInterface_init(PyObject *, PyObject *);}
static PyObject *meth_trikControl_ObjectSensorInterface_init(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        bool a0;
        trikControl::ObjectSensorInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_trikControl_ObjectSensorInterface, &sipCpp, &a0))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_ObjectSensorInterface, sipName_init);
                return NULL;
            }

            sipCpp->init(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ObjectSensorInterface, sipName_init, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_ObjectSensorInterface_detect(PyObject *, PyObject *);}
static PyObject *meth_trikControl_ObjectSensorInterface_detect(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::ObjectSensorInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_ObjectSensorInterface, &sipCpp))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_ObjectSensorInterface, sipName_detect);
                return NULL;
            }

            sipCpp->detect();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ObjectSensorInterface, sipName_detect, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_ObjectSensorInterface_read(PyObject *, PyObject *);}
static PyObject *meth_trikControl_ObjectSensorInterface_read(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::ObjectSensorInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_ObjectSensorInterface, &sipCpp))
        {
            QVector<int>*sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_ObjectSensorInterface, sipName_read);
                return NULL;
            }

            sipRes = new QVector<int>(sipCpp->read());

            return sipConvertFromNewType(sipRes,sipType_QVector_1800,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ObjectSensorInterface, sipName_read, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_ObjectSensorInterface_stop(PyObject *, PyObject *);}
static PyObject *meth_trikControl_ObjectSensorInterface_stop(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::ObjectSensorInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_ObjectSensorInterface, &sipCpp))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_ObjectSensorInterface, sipName_stop);
                return NULL;
            }

            sipCpp->stop();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ObjectSensorInterface, sipName_stop, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_ObjectSensorInterface_getDetectParameters(PyObject *, PyObject *);}
static PyObject *meth_trikControl_ObjectSensorInterface_getDetectParameters(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const trikControl::ObjectSensorInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_ObjectSensorInterface, &sipCpp))
        {
            QVector<int>*sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_ObjectSensorInterface, sipName_getDetectParameters);
                return NULL;
            }

            sipRes = new QVector<int>(sipCpp->getDetectParameters());

            return sipConvertFromNewType(sipRes,sipType_QVector_1800,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ObjectSensorInterface, sipName_getDetectParameters, NULL);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_trikControl_ObjectSensorInterface(void *, int);}
static void release_trikControl_ObjectSensorInterface(void *sipCppV,int)
{
    trikControl::ObjectSensorInterface *sipCpp = reinterpret_cast<trikControl::ObjectSensorInterface *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_trikControl_ObjectSensorInterface(sipSimpleWrapper *);}
static void dealloc_trikControl_ObjectSensorInterface(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_trikControl_ObjectSensorInterface(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_trikControl_ObjectSensorInterface[] = {{141, 0, 1}};


static PyMethodDef methods_trikControl_ObjectSensorInterface[] = {
    {SIP_MLNAME_CAST(sipName_detect), meth_trikControl_ObjectSensorInterface_detect, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_getDetectParameters), meth_trikControl_ObjectSensorInterface_getDetectParameters, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_init), meth_trikControl_ObjectSensorInterface_init, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_read), meth_trikControl_ObjectSensorInterface_read, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_stop), meth_trikControl_ObjectSensorInterface_stop, METH_VARARGS, NULL}
};


/* Define this type's signals. */
static const pyqt4QtSignal signals_trikControl_ObjectSensorInterface[] = {
    {"stopped()", 0, 0, 0},
    {0, 0, 0, 0}
};


pyqt4ClassTypeDef sipTypeDef_trikControl_trikControl_ObjectSensorInterface = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_trikControl__ObjectSensorInterface,
        {0}
    },
    {
        sipNameNr_ObjectSensorInterface,
        {0, 255, 0},
        5, methods_trikControl_ObjectSensorInterface,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_trikControl_ObjectSensorInterface,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_trikControl_ObjectSensorInterface,
    0,
    0,
    0,
    release_trikControl_ObjectSensorInterface,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    &trikControl::ObjectSensorInterface::staticMetaObject,
    0,
    signals_trikControl_ObjectSensorInterface,
};
