/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 */

#include "sipAPItrikControl.h"

#line 10 "GamepadFactory.sip"
			#include <gamepadFactory.h>
#line 12 "./siptrikControltrikNetworkGamepadFactory.cpp"

#line 9 "GamepadInterface.sip"
		#include <gamepadInterface.h>
#line 16 "./siptrikControltrikNetworkGamepadFactory.cpp"


extern "C" {static PyObject *meth_trikNetwork_GamepadFactory_create(PyObject *, PyObject *);}
static PyObject *meth_trikNetwork_GamepadFactory_create(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "i", &a0))
        {
            trikNetwork::GamepadInterface*sipRes;

            sipRes = trikNetwork::GamepadFactory::create(a0);

            return sipConvertFromType(sipRes,sipType_trikNetwork_GamepadInterface,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_GamepadFactory, sipName_create, NULL);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_trikNetwork_GamepadFactory(void *, int);}
static void release_trikNetwork_GamepadFactory(void *sipCppV,int)
{
    delete reinterpret_cast<trikNetwork::GamepadFactory *>(sipCppV);
}


extern "C" {static void assign_trikNetwork_GamepadFactory(void *, SIP_SSIZE_T, const void *);}
static void assign_trikNetwork_GamepadFactory(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<trikNetwork::GamepadFactory *>(sipDst)[sipDstIdx] = *reinterpret_cast<const trikNetwork::GamepadFactory *>(sipSrc);
}


extern "C" {static void *array_trikNetwork_GamepadFactory(SIP_SSIZE_T);}
static void *array_trikNetwork_GamepadFactory(SIP_SSIZE_T sipNrElem)
{
    return new trikNetwork::GamepadFactory[sipNrElem];
}


extern "C" {static void *copy_trikNetwork_GamepadFactory(const void *, SIP_SSIZE_T);}
static void *copy_trikNetwork_GamepadFactory(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new trikNetwork::GamepadFactory(reinterpret_cast<const trikNetwork::GamepadFactory *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_trikNetwork_GamepadFactory(sipSimpleWrapper *);}
static void dealloc_trikNetwork_GamepadFactory(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_trikNetwork_GamepadFactory(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_type_trikNetwork_GamepadFactory(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_trikNetwork_GamepadFactory(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    trikNetwork::GamepadFactory *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new trikNetwork::GamepadFactory();

            return sipCpp;
        }
    }

    {
        const trikNetwork::GamepadFactory* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_trikNetwork_GamepadFactory, &a0))
        {
            sipCpp = new trikNetwork::GamepadFactory(*a0);

            return sipCpp;
        }
    }

    return NULL;
}


static PyMethodDef methods_trikNetwork_GamepadFactory[] = {
    {SIP_MLNAME_CAST(sipName_create), meth_trikNetwork_GamepadFactory_create, METH_VARARGS, NULL}
};


pyqt4ClassTypeDef sipTypeDef_trikControl_trikNetwork_GamepadFactory = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_trikNetwork__GamepadFactory,
        {0}
    },
    {
        sipNameNr_GamepadFactory,
        {18, 255, 0},
        1, methods_trikNetwork_GamepadFactory,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    -1,
    0,
    0,
    init_type_trikNetwork_GamepadFactory,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_trikNetwork_GamepadFactory,
    assign_trikNetwork_GamepadFactory,
    array_trikNetwork_GamepadFactory,
    copy_trikNetwork_GamepadFactory,
    release_trikNetwork_GamepadFactory,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
