/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 */

#include "sipAPItrikControl.h"

#line 6 "LedInterface.sip"
		#include <ledInterface.h>
#line 9 "BatteryInterface.sip"
		#include <batteryInterface.h>
#line 14 "./siptrikControltrikControlBatteryInterface.cpp"

#line 26 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 18 "./siptrikControltrikControlBatteryInterface.cpp"
#line 368 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 21 "./siptrikControltrikControlBatteryInterface.cpp"
#line 351 "/usr/share/sip/PyQt4//QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 24 "./siptrikControltrikControlBatteryInterface.cpp"
#line 29 "/usr/share/sip/PyQt4//QtCore/qobject.sip"
#include <qobject.h>
#line 27 "./siptrikControltrikControlBatteryInterface.cpp"
#line 269 "/usr/share/sip/PyQt4//QtCore/qvariant.sip"
#include <qvariant.h>
#line 30 "./siptrikControltrikControlBatteryInterface.cpp"
#line 28 "/usr/share/sip/PyQt4//QtCore/qlist.sip"
#include <qlist.h>
#line 33 "./siptrikControltrikControlBatteryInterface.cpp"
#line 32 "/usr/share/sip/PyQt4//QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 36 "./siptrikControltrikControlBatteryInterface.cpp"
#line 30 "/usr/share/sip/PyQt4//QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 39 "./siptrikControltrikControlBatteryInterface.cpp"
#line 115 "/usr/share/sip/PyQt4//QtCore/qlist.sip"
#include <qlist.h>
#line 42 "./siptrikControltrikControlBatteryInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qthread.sip"
#include <qthread.h>
#line 45 "./siptrikControltrikControlBatteryInterface.cpp"
#line 31 "/usr/share/sip/PyQt4//QtCore/qstring.sip"
#include <qstring.h>
#line 48 "./siptrikControltrikControlBatteryInterface.cpp"
#line 30 "/usr/share/sip/PyQt4//QtCore/qregexp.sip"
#include <qregexp.h>
#line 51 "./siptrikControltrikControlBatteryInterface.cpp"
#line 26 "/usr/share/sip/PyQt4//QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 54 "./siptrikControltrikControlBatteryInterface.cpp"


extern "C" {static PyObject *meth_trikControl_BatteryInterface_readVoltage(PyObject *, PyObject *);}
static PyObject *meth_trikControl_BatteryInterface_readVoltage(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::BatteryInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_BatteryInterface, &sipCpp))
        {
            float sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_BatteryInterface, sipName_readVoltage);
                return NULL;
            }

            sipRes = sipCpp->readVoltage();

            return PyFloat_FromDouble((double)sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_BatteryInterface, sipName_readVoltage, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_trikControl_BatteryInterface_readRawDataVoltage(PyObject *, PyObject *);}
static PyObject *meth_trikControl_BatteryInterface_readRawDataVoltage(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        trikControl::BatteryInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_trikControl_BatteryInterface, &sipCpp))
        {
            float sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_BatteryInterface, sipName_readRawDataVoltage);
                return NULL;
            }

            sipRes = sipCpp->readRawDataVoltage();

            return PyFloat_FromDouble((double)sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_BatteryInterface, sipName_readRawDataVoltage, NULL);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_trikControl_BatteryInterface(void *, int);}
static void release_trikControl_BatteryInterface(void *sipCppV,int)
{
    trikControl::BatteryInterface *sipCpp = reinterpret_cast<trikControl::BatteryInterface *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_trikControl_BatteryInterface(sipSimpleWrapper *);}
static void dealloc_trikControl_BatteryInterface(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_trikControl_BatteryInterface(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_trikControl_BatteryInterface[] = {{141, 0, 1}};


static PyMethodDef methods_trikControl_BatteryInterface[] = {
    {SIP_MLNAME_CAST(sipName_readRawDataVoltage), meth_trikControl_BatteryInterface_readRawDataVoltage, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_readVoltage), meth_trikControl_BatteryInterface_readVoltage, METH_VARARGS, NULL}
};


pyqt4ClassTypeDef sipTypeDef_trikControl_trikControl_BatteryInterface = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_trikControl__BatteryInterface,
        {0}
    },
    {
        sipNameNr_BatteryInterface,
        {0, 255, 0},
        2, methods_trikControl_BatteryInterface,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_trikControl_BatteryInterface,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_trikControl_BatteryInterface,
    0,
    0,
    0,
    release_trikControl_BatteryInterface,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    &trikControl::BatteryInterface::staticMetaObject,
    0,
    0
};
