/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 */

#include "sipAPItrikControl.h"

#line 6 "DeviceInterface.sip"
		#include <deviceInterface.h>
#line 12 "./siptrikControltrikControlDeviceInterface.cpp"



/* Call the instance's destructor. */
extern "C" {static void release_trikControl_DeviceInterface(void *, int);}
static void release_trikControl_DeviceInterface(void *sipCppV,int)
{
    delete reinterpret_cast<trikControl::DeviceInterface *>(sipCppV);
}


extern "C" {static void dealloc_trikControl_DeviceInterface(sipSimpleWrapper *);}
static void dealloc_trikControl_DeviceInterface(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_trikControl_DeviceInterface(sipGetAddress(sipSelf),0);
    }
}

static sipEnumMemberDef enummembers_trikControl_DeviceInterface[] = {
    {sipName_failure, static_cast<int>(trikControl::DeviceInterface::failure), 4},
    {sipName_off, static_cast<int>(trikControl::DeviceInterface::off), 4},
    {sipName_ready, static_cast<int>(trikControl::DeviceInterface::ready), 4},
    {sipName_starting, static_cast<int>(trikControl::DeviceInterface::starting), 4},
    {sipName_stopping, static_cast<int>(trikControl::DeviceInterface::stopping), 4},
};


pyqt4ClassTypeDef sipTypeDef_trikControl_trikControl_DeviceInterface = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_CLASS,
        sipNameNr_trikControl__DeviceInterface,
        {0}
    },
    {
        sipNameNr_DeviceInterface,
        {0, 255, 0},
        0, 0,
        5, enummembers_trikControl_DeviceInterface,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_trikControl_DeviceInterface,
    0,
    0,
    0,
    release_trikControl_DeviceInterface,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
